/// <reference types="cypress" />

describe('Task', () => {
  it('Create task', () => {
    cy.visit('http://localhost:5173')
    cy.get('button[type="submit"]').click()
    cy.get('input[id="login"]').type('jadminowy')
    cy.get('input[id="psw"]').type('JanAdminowy1!')
    cy.get('button[type="submit"]').click()
    cy.get(':nth-child(1) > .nav-link').click()
    cy.get('.p-4 > .btn').click()
    cy.get('#name').type('Test Project')
    cy.get('#desc').type('This is a test project description for taks.')
    cy.get('.form-container > .btn').click()
    cy.get('tbody > tr > :nth-child(1)').contains('Test Project')
    cy.get('select').select('Test Project')
    //project created, now create story
    cy.wait(1000)
    cy.get(':nth-child(2) > .nav-link').click()
    cy.wait(1000)
    cy.get('.p-4 > .btn').click()
    cy.get('#name').type('Test Story')
    cy.get('#desc').type('This is a test story description. for task.')
    cy.get('form > button').click()
    cy.get('tbody > tr > :nth-child(1)').contains('Test Story')
    //create task
    cy.get('.toggle-arrow > td').click()
    cy.get('.p-4 > div > .btn').click()
    cy.get('#name').type('Test task')
    cy.get('#desc').type('This is a test task description.')
    cy.get('#estTime').type('2027-01-01')
    cy.get('form > .btn').click()
    cy.get('tbody > :nth-child(1) > :nth-child(1)').contains('Test Story')
    cy.get('.toggle-arrow > td').click()
    //edit task
    cy.get('.task-buttons > :nth-child(2)').click()
    cy.get('#name').clear().type('Updated Test Task')
    cy.get('#desc').clear().type('This is an updated test task description.')
    cy.get('#prio').select('HIGH')
    cy.get('#estTime').type('2028-01-02')
    cy.get('.submit-btn').click()
    cy.get('.toggle-arrow > td').click()
    cy.get('.task-buttons > :nth-child(3)').click()
    cy.get('#signedUser').select('Michał Developerowy (Developer)')
    cy.get('#state').select('INPROGRESS')
    cy.get('form > button').click()
    cy.get('.toggle-arrow > td').click()
    cy.get('[colspan="7"] > .d-flex > .p-4 > .table > tbody > tr > :nth-child(2)').contains(
      'Updated Test Task',
    )
    //delete task
    cy.get('.task-buttons > .btn-danger').click()
    cy.get('.delete-btn').click()
    cy.get('.toggle-arrow > td').click()
    cy.get('.toggle-arrow > td').should('not.contain', 'Updated Test Task')
    cy.get(':nth-child(7) > .btn').click()
    cy.get('.delete-btn').click()
    cy.get(':nth-child(1) > .nav-link').click()
    cy.get(':nth-child(5) > .btn').click()
    cy.get('.delete-btn').click()
  })
})
